### ISSUE TITLE
tweakable crashes

### ISSUE THREAD

**Issue by dafhi** [glasyalabolas/fb-image-resize-demo#1]

**Comment by countingpine** [comment]
Tested in Windows 7 32-bit.
It seems the program hangs in a "locked screen" state.
Uncommenting the `screenlock` and running with `-g -exx` gives a segmentation violation error in `resizeImage()`.

**Comment by glasyalabolas** [comment]
An off-by-one error, I'm afraid =D

It should be fixed now.
